name: Build and deploy Client to Azure Web Apps

env:
  AZURE_WEBAPP_NAME: satisfactory-accounting         # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'                     # set this to the path to your web app project, defaults to the repository root

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-dotnet-project.yml
    with:
      project-path: SatisfactoryAccountingData.Client
      dotnet-version: '6.0.x'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{needs.build.outputs.artifact-name}}

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
