name: Build and deploy API to Azure Functions

env:
  AZURE_FUNCTIONS_NAME: satisfactory-accounting-data   # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'                       # set this to the path to your web app project, defaults to the repository root
  ARTIFACT_NAME: dotnet-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-dotnet-project.yml
    with:
      project-path: SatisfactoryAccountingData
      dotnet-version: '6.0.x'
      artifact-name: ${{ env.ARTIFACT_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-functions.outputs.webapp-url }}/api/swagger/ui
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-functions
        with:
          app-name: ${{ env.AZURE_FUNCTIONS_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
