name: Build and deploy API to Azure Functions

env:
  AZURE_FUNCTIONS_NAME: satisfactory-accounting-data   # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'                       # set this to the path to your web app project, defaults to the repository root

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-dotnet-project.yml
    with:
      project-path: SatisfactoryAccountingData
      dotnet-version: '6.0.x'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}/api/swagger/ui
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{needs.build.outputs.artifact-name}}

      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
      - name: Check paths
        run: |
           pwd
           echo ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
           echo ${{needs.build.outputs.artifact-name}}
           echo '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{needs.build.outputs.artifact-name}}'
           la -la ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{needs.build.outputs.artifact-name}}

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        id: deploy-to-functions
        with:
          app-name: ${{ env.AZURE_FUNCTIONS_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/${{needs.build.outputs.artifact-name}}
