name: Build and Test

on:
  workflow_call:
    inputs:
      project-path:
        required: true
        type: string
      dotnet-version:
        required: true
        type: string
    outputs:
      artifact-name:
        description: "Name of created artifact"
        value: ${{ jobs.build-and-test.outputs.artifact-name }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      artifact-name: dotnet-app
    outputs:
      artifact-name: ${{env.artifact-name}}
    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      
      - name: Set up dependency caching for faster builds
        uses: actions/cache@v2
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-
      
      - name: dotnet restore
        run: dotnet restore
      
      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore
        
      - name: dotnet test
        run: dotnet test --logger trx --results-directory "TestResults" --no-restore

      - name: dotnet publish
        run: dotnet publish ${{inputs.project-path}} -c Release -o ${{env.DOTNET_ROOT}}/myapp --no-restore

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.artifact-name}}
          path: ${{env.DOTNET_ROOT}}/myapp
